### ISSUE TITLE
This site can't be reached on http://localhost:9876

### ISSUE THREAD

**Issue by luminusian** [bensu/doo#129]
https://github.com/bensu/doo says,
>Alternatively, if you don't want doo to launch the browsers for you, you can always launch them yourself and navigate to http://localhost:9876

With karma "1.5.0", `lein doo` gives an error:
```
ERROR [plugin]: Cannot find plugin "karma-chrome-launcher".
  Did you forget to install it?

```
http://localhost:9876 says,
`This site can't be reached`

With karma "0.13.19", `lein doo` gives a warning:
`WARN [plugin]: Cannot find plugin "karma-chrome-launcher".`

http://localhost:9876 says,
`Karma v0.13.19 - connected`

**Comment by miikka** [comment]
Please try installing the Karma plugin `karma-chrome-launcher` with `npm install karma-chrome-launcher --save-dev` and see if that helps.

Since this is pretty old issue already, I assume that you've moved on and I'm going to close this. If it's still a problem and installing the plugin doesn't solve it, please re-open this issue with more information.
