### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by matthiasn** [bensu/doo#147]
Hi, for a while, **doo** has served me well, thanks for that. But now I'm running into more and more issues, e.g. with the latest Clojure versions, and looking at the issues piling up here, I wonder if you have plans to keep maintaining this library? Thanks, Matthias

**Comment by miikka** [comment]
I'd be happy to spend some time on getting the open pull requests merged (which I believe would already fix the most pressing issues) and on creating a new release, if that helps, but somebody with the keys to the kingdom (i.e. GitHub and Clojars access) needs to be involved.

In the meantime, I noticed that Kira Systems is maintaining a fork at [kirasystems/doo](https://github.com/kirasystems/doo).

**Comment by bensu** [comment]
@miikka I'll give you access now

**Comment by bensu** [comment]
I'm planning to do a pass to do three things:

- update to the latest Clojure(Script) versions
- merge in outstanding PRs
- add Chrome headless

but if @miikka wants to work on any of those first, please go ahead.

**Comment by miikka** [comment]
That's a good plan! I'm going to start with Clojure and ClojureScript updates already.

**Comment by miikka** [comment]
I've now merged #141 to make doo work again with the latest ClojureScript, #143 to add support for managed dependencies, and #136 to add support for Headless Chrome. I believe that the Clojure 1.9 problems are caused by [CLJS-2352](https://dev.clojure.org/jira/browse/CLJS-2352), which will be fixed in the next ClojureScript release.

The rest of the open PRs look good, too, but looks like they need some work before merging. This could be a good time for a bug-fixing release.

**Comment by vemv** [comment]
Happy to see all this progress lately!

Looking forward to a new Clojars release as I'd want to try out chrome-headless.

Cheers - Victor

**Comment by MatthewDarling** [comment]
Regarding the fork at [kirasystems/doo](https://github.com/kirasystems/doo), the only goal we had with that was to merge #141 and #143 so we could integrate `doo` to our CI. Since those have been merged here, the fork's days are numbered :)

If there's anything we should change to let people know "hey go use the main project, not this fork", happy to do that. And of course, it's great to see more activity here in the main repo.

**Comment by miikka** [comment]
@bensu, I'd like to do a release now. Can you do it, or can you give me access to doo and lein-doo on Clojars so I can do it? (I'm [miikka](https://clojars.org/miikka) over there as well.)

**Comment by bensu** [comment]
@miikka great! Added you in both groups. Let me know if you need anything else

**Comment by miikka** [comment]
`[doo "0.1.8"]` and `[lein-doo "0.1.8"]` are now available on Clojars. 🎉

**Comment by matthiasn** [comment]
Great, working again, thanks!
