### ISSUE TITLE
Integration Tests?

### ISSUE THREAD

**Issue by xcthulhu** [bensu/doo#30]
Would it be at all possible for `doo` to make client-server integration testing more convenient, or is that out of scope?

It looks like the way to do it in `lein` is to have an alias where you spin up a ring server, run your tests, and spin the ring server back down:
https://groups.google.com/d/msg/clojurescript/rArkEBCRods/Bqo4IE5ehNUJ

Anyhow this is a marvelous library and I am looking forward to using it in all of my ClojureScript projects!

**Comment by xcthulhu** [comment]
That poster to the ClojureScript mailing list is pretty clever BTW :D

**Comment by bensu** [comment]
It's not out of scope but it is not in the near future either. I implemented a bunch of functionality for browser testing and there are many corner cases to handle yet. After that I might consider implementing this and other new features. In the meantime, PRs are very welcome.

As for the implementations, in the google groups post I offered two but I only see place in `doo` for something similar to the second one: initializing a server, calling the cljs tests, and then stopping the server.

**Comment by viesti** [comment]
I did a trial with `doo` and your other project, `cljs-react-test`, by using [`doo/run-script`](https://github.com/viesti/shopping-list/blob/master/test/clj/shopping_list/e2e.clj#L49) in a `clojure.test` for which I have fixture that spins up&down my server (Stuart Sierra's [component](https://github.com/stuartsierra/component) makes handling dependencies easy). Before the test I compile CLJS files with a specific runner that selects only e2e style tests.

 Had to setup CORS (since the runner takes a local file) to make AJAX work, but that was [relatively easy too](https://github.com/viesti/shopping-list/blob/master/test/clj/shopping_list/e2e.clj#L26) (using [Duct](https://github.com/weavejester/duct) here).

Anyhow, I kinda liked the experiment (also `doo` and `cljs-react-test` :)) and just saying that `doo` as a library might give you enough control to wire things together in a "normal" unit test :)

**Comment by bensu** [comment]
Thanks @viesti! That's great news. Looking at the code, I agree it can be done using `doo.core/run-script` without much fuzz. Maybe there is a way to extract the boiler plate from that so that doo makes it even easier and people start doing it. Otherwise, we can properly document your findings in a tutorial.

**Comment by viesti** [comment]
Thanks! :) I'm thinking that a short tutorial might be good (or a mention in the readme if this get's short enough) since the wiring might be a bit related to the app architecture. There are at least these points:

1. clojure.test which compiles a suitable runner and calls `doo/run-script` (this is generic, clojure.test is a good starting point)
2. Fixture that start&stops the app (might be app specific, thinking a let expression around the test function for setup&teardown)
3. CORS setup (depends on the app, but providing an example helps)
4. Related to previous, I needed a way to tell the CLJS app the location of the server in the test. Solved it by provicing a test/production version of config.cljs that has a suitable base url (depends on the app I'd say :))

**Comment by viesti** [comment]
So had sort of a flow (and kids sleeping too :)) and wipped up a "tutorial" in a PR: https://github.com/bensu/doo/pull/65. Hope it makes any sense :)

**Comment by bensu** [comment]
@xcthulhu did you find the [wiki article](https://github.com/bensu/doo/wiki/End-to-end-testing-example) useful?

**Comment by xcthulhu** [comment]
@bensu TBH the wiki article is overly complicated.  It never really says what `my-app.system` is... I take it it's just taken from some project.  I've yet to translate this into my own stack.

**Comment by bensu** [comment]
@xcthulhu I edited the wiki to have a slower pace and explained a few of the requirements. Closing this for now.
