### ISSUE TITLE
"Unable to resolve symbol: update in this context, compiling:(leiningen/doo.clj:99:35)"

### ISSUE THREAD

**Issue by jrheard** [bensu/doo#36]
hi!

this is my first time opening a github issue, please excuse me if i'm doing any of this wrong.

my build on travis-ci just started failing with the message in this issue's subject line. full traceback at https://s3.amazonaws.com/archive.travis-ci.org/jobs/82362310/log.txt . i'm unable to reproduce this locally, but that's probably because i'm not doing a good enough job of blowing away my currently downloaded libraries or something, i imagine that travis is running the most recent version of doo while i'm running an older version.

i see the string "(update" occur in 9c60f648b01f5e3c21244dfbf67684f22ce3a5c1 , and this just started happening for me, so i'm betting that this behavior was introduced in that commit.

i wish i could give you easy repro steps - is this not happening on your machine?

thanks!

**Comment by jrheard** [comment]
my code's at https://github.com/jrheard/cljstone and my build history is at https://travis-ci.org/jrheard/cljstone/builds , if that's at all helpful.

**Comment by bensu** [comment]
Hi @jrheard,

The issue is exactly what I need, thanks!

To delete `doo` from your machine in Ubuntu: `rm -r ~/.m2/repository/lein-doo/ ~/.m2/repository/doo/`.

The problem is probably in Travis' Lein version. The function `update` was added in Clojure 1.7 and only the latest Leiningen uses it. My bad. I changed all `update` functions for `update-in` to be backwards compatible again. Try again and you should see the new SNAPSHOT version: 

`lein-doo/lein-doo/0.1.5-SNAPSHOT/lein-doo-0.1.5-20150927.085031-3.jar`

Close the issue if the problem is solved :)

I apologize for the breakage but it is to be expected from SNAPSHOT versions. If you are using `phantom` you can always go back to `[lein-doo 0.1.4]` to get the same features and none of the instability.

**Comment by jrheard** [comment]
ah, that makes tons of sense - i saw that `update` was added in 1.7, but didn't do the full amount of digging required to compare travis's lein's version vs. the version that started using 1.7. everything looks great now, thanks for the fix! thanks also for the caution re: snapshot releases - my project is just a toy, so i totally don't mind dealing with occasional breaks. thanks again for your work on this project!
